# Generated by Django 5.0.2 on 2025-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_part_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='stl_file',
            field=models.FileField(blank=True, upload_to='stl_files/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='thumbnail',
            field=models.ImageField(blank=True, default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasedpart',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedpart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchasedpart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
