# Generated by Django 5.0.2 on 2025-04-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_material_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, help_text='Manufacturer or brand name', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total cost of the material', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, help_text='Link to purchase or product page'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total weight in grams', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='material_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, help_text='Default color for this material (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, help_text='Cost per kilogram in your local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.DecimalField(decimal_places=3, help_text='Density in grams per cubic centimeter (g/cm³)', max_digits=10),
        ),
    ]
