# Generated by Django 5.0.2 on 2025-04-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_material_brand_material_cost_material_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of the material', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Density in grams per cubic centimeter (g/cm³)', max_digits=10, null=True),
        ),
    ]
