# Generated by Django 5.0.2 on 2025-04-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_material_cost_alter_material_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kilogram in your local currency', max_digits=10, null=True),
        ),
    ]
