# Generated by Django 5.0.2 on 2025-04-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_material_cost_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost_per_kg',
        ),
    ]
