# Generated by Django 5.0.2 on 2025-04-15 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for this instruction step', upload_to='instructions/')),
                ('description', models.TextField(help_text='Description of this instruction step')),
                ('order', models.IntegerField(help_text='Order in which this instruction should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Instructions',
                'ordering': ['order'],
            },
        ),
    ]
