# Generated by Django 5.0.2 on 2025-04-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this instruction step'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this instruction should be displayed'),
        ),
    ]
