# Generated by Django 5.0.2 on 2025-05-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_machine_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlicedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sliced_files/')),
                ('slicer', models.CharField(choices=[('cura', 'Cura'), ('prusaslicer', 'PrusaSlicer'), ('other', 'Other')], default='cura', max_length=20)),
                ('layer_height', models.FloatField(blank=True, help_text='Layer height in mm', null=True)),
                ('infill_percentage', models.IntegerField(blank=True, help_text='Infill percentage', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliced_files', to='projects.machine')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliced_files', to='projects.material')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliced_files', to='projects.part')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
