# Generated by Django 5.0.2 on 2025-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_slicedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, help_text='Link to where the project files were sourced from', max_length=500),
        ),
        migrations.DeleteModel(
            name='SlicedFile',
        ),
    ]
