# Generated by Django 5.2.14 on 2026-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_change_instructions_image_to_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='settings_type',
            field=models.CharField(choices=[('general', 'General Settings'), ('appearance', 'Appearance Settings'), ('machines', 'Machine Settings')], max_length=50),
        ),
    ]
