# Generated by Django 5.2.14 on 2026-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_usersettings_settings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PLA+', 'PLA+'), ('PLA-CF', 'PLA Carbon Fiber'), ('PLA-GF', 'PLA Glass Fiber'), ('PLA-Silk', 'PLA Silk'), ('ABS', 'ABS'), ('ABS-GF', 'ABS Glass Fiber'), ('ABS-CF', 'ABS Carbon Fiber'), ('PETG', 'PETG'), ('PETG-CF', 'PETG Carbon Fiber'), ('PETG-GF', 'PETG Glass Fiber'), ('PCTG', 'PCTG'), ('TPU', 'TPU'), ('TPE', 'TPE'), ('Nylon', 'Nylon (PA)'), ('PA-CF', 'PA Carbon Fiber'), ('PA-GF', 'PA Glass Fiber'), ('PC', 'Polycarbonate (PC)'), ('PC-CF', 'PC Carbon Fiber'), ('ASA', 'ASA'), ('HIPS', 'HIPS'), ('PVA', 'PVA'), ('BVOH', 'BVOH'), ('PP', 'Polypropylene (PP)'), ('PEEK', 'PEEK'), ('PEKK', 'PEKK'), ('PEI', 'PEI (Ultem)'), ('POM', 'POM (Delrin)'), ('Resin', 'Standard Resin'), ('Resin-Tough', 'Tough Resin'), ('Resin-Flex', 'Flexible Resin'), ('Resin-Cast', 'Castable Resin'), ('Resin-Water', 'Water Washable Resin'), ('Other', 'Other')], default='PLA', max_length=20),
        ),
    ]
