# Generated by Django 5.2.14 on 2026-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, help_text='Total cost of the material', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Total weight in grams', max_digits=10),
        ),
    ]
