# Generated by Django 5.2.14 on 2026-05-12 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_material_cost_alter_material_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IP address of the printer on the local network', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='mqtt_access_code',
            field=models.CharField(blank=True, help_text='Access code for MQTT authentication', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='filament_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filament weight for one copy in grams', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='print_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='print_time_seconds',
            field=models.IntegerField(blank=True, help_text='Total print time for one copy in seconds', null=True),
        ),
        migrations.CreateModel(
            name='UnclaimedSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('print_time_seconds', models.IntegerField(blank=True, null=True)),
                ('filament_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filament_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unclaimed_slices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
