# Generated by Django 5.2.14 on 2026-05-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_machine_ip_address_machine_mqtt_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unclaimedslice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='settings_type',
            field=models.CharField(choices=[('general', 'General Settings'), ('appearance', 'Appearance Settings'), ('api', 'API Security Settings'), ('machines', 'Machine Settings')], max_length=50),
        ),
    ]
