# Generated by Django 5.2.14 on 2026-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_unclaimedslice_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='assigned_slice_filename',
            field=models.CharField(blank=True, help_text='Filename of the assigned slice for exact MQTT tracking', max_length=255),
        ),
    ]
