# Generated by Django 5.2.14 on 2026-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_part_assigned_slice_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this machine was seen online', null=True),
        ),
    ]
