# Generated by Django 5.2.14 on 2026-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_printhistory_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
