# Generated by Django 5.2.14 on 2026-05-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_projectimage_options_projectimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_parts', to='projects.part'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='settings_type',
            field=models.CharField(choices=[('general', 'General Settings'), ('appearance', 'Appearance Settings'), ('api', 'API Security Settings'), ('machines', 'Machine Settings'), ('system', 'System Settings')], max_length=50),
        ),
    ]
