version: 2

python:
  install:
    - method: pip
      path: .

# Configure Sphinx
sphinx:
  configuration: docs/conf.py

# Define the formats you want to build
formats:
  - htmlzip
  # - pdf
  # - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10" # Specify your desired Python version
  jobs:
    pre_build:
      # Install project dependencies
      - "pip install -r requirements.txt"
      # Install documentation dependencies
      - "pip install -r docs/requirements.txt"
      # You might need to install other system dependencies here if your docs need them
      # - "sudo apt-get update && sudo apt-get install -y ..." 